### ISSUE TITLE
Allow configuring the details included in the comment

### ISSUE THREAD

**Issue by gziolo** [WordPress/props-bot-action#38]
### Problem

See https://github.com/WordPress/props-bot-action/pull/21#discussion_r1474084251.

This is how part of the comment looks like today:

<img width="861" alt="Screenshot 2024-02-01 at 13 13 28" src="https://github.com/WordPress/props-bot-action/assets/699132/8e4e8d07-433e-4f48-88a8-b1f3ad05b692">

### Feature Request

Would it be possible to make this configurable? While Core SVN makes perfect sense in WordPress develop, the GitHub Merge isn't that useful. Then, when contributing to Gutenberg, it was exactly the other way around. So, while the default could be as is, what if you could pass the setting when defining the GitHub workflow?

```
svnProps: true
gitCoAuthored: true
```

**Comment by desrosj** [comment]
Thanks @gziolo! 

I think this is reasonable. But, there's one scenario that comes to mind, though.

In WordPress/wordpress-develop, it's not uncommon for change suggestions in a PR to be copied over into a Gutenberg one. In that scenario, would it be helpful for the maintainer to have the GitHub-flavored list in order to include it in the Gutenberg merge?

Maybe we could add the ability to tell props bot to include both formats somehow. Maybe a `props-bot-both` label or something?

**Comment by gziolo** [comment]
> In WordPress/wordpress-develop, it's not uncommon for change suggestions in a PR to be copied over into a Gutenberg one. 

I didn't consider that scenario. Interesting. Maybe it's best to keep both for now and see whether it creates too much noise.

**Comment by noisysocks** [comment]
Didn't see this issue before opening https://github.com/WordPress/props-bot-action/issues/47.

I think it's currently far too noisy having both lists. At the very least we could collapse the non-relevant one behind a `<detail>`.

**Comment by noisysocks** [comment]
> In WordPress/wordpress-develop, it's not uncommon for change suggestions in a PR to be copied over into a Gutenberg one. In that scenario, would it be helpful for the maintainer to have the GitHub-flavored list in order to include it in the Gutenberg merge?

I think you're over-optimising for an edge case here 😀 It's much much much more common (~20 new PRs are opened in Gutenberg every day) that you don't want this extra information than that you do want it.
