### ISSUE TITLE
Only list reviewers who actively reviewed

### ISSUE THREAD

**Issue by swissspidy** [WordPress/props-bot-action#56]
### Problem

I noticed that just requesting review from someone adds them to the props list, even though they never actually left any review/comment on the PR, for example because they are on vacation.

### Feature Request

Reviewers should only be added to props after actually leaving comments on a PR or approving it.

### Workaround

Manually remove them from the props list again.

**Comment by desrosj** [comment]
@swissspidy Do you have a workflow run that you can link to?

In my testing, only submitted reviews are added. To test, I added myself as a reviewer for #55 and manually reran the test workflow and I'm not seeing myself in the [raw data returned by the GraphQL query](https://github.com/WordPress/props-bot-action/actions/runs/7779919321/job/21229886648#step:3:23).

The bot doesn't comment on the PR in this repo because the event still needs to be switched to `pull_request_target` for the repo's actual test workflow.

Is it possible the person commented on an issue that's linked to the PR? Anyone who comments on or creates issues that are linked will be added to the list as well.

**Comment by swissspidy** [comment]
Hmm I can't remember the PR anymore where I noticed this, but it doesn't seem to happen anymore on the newer PRs I saw 🤔 

So I suppose it's like you said, someone commented on a linked issue somewhere and I didn't see that.

Closing for now 👍
